name: delaunay
description: Delaunay triangulation.
version: 0.1.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

#dependencies:
#  path: ^1.6.0

dev_dependencies:
  args: ^1.6.0
  pedantic: ^1.8.0
  test: ^1.6.0
