name: Tests
on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image:  google/dart:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: pub get
      - name: Format
        run: dartfmt --set-exit-if-changed .
      - name: Analyze
        run: dartanalyzer .
      - name: Test
        run: pub run test
      - name: Run example
        run: dart example/delaunay_example.dart
